eng:
  description: Do you even code, bro?

not-eng:
  description: no nerds allowed.

product:
  description: no nerds allowed.

backend:
  description: no nerds allowed.

frontend:
  description: no nerds allowed.

watchdog:
  description: no nerds allowed.


