engineering:
  description: Do you even code, bro?
  members:
    - github: tiki-bot
    - github: mike-audi

product:
  description: no nerds allowed.
  members:
    - github: tiki-bot
    - github: mike-audi

backend:
  description: those who build the infrastructure
  parent: engineering
  parentSlug: engineering
  members:
    - github: tiki-bot
    - github: mike-audi

frontend:
  description: those who build the things customers touch
  parent: engineering
  parentSlug: engineering
  members:
    - github: tiki-bot

sysadmin:
  description: escalations and monitoring
  members:
    - github: mike-audi

