name: 'Team Sync'
on:
  push:
    branches:
      - main
    paths:
      - '.github/teams.yml'

jobs:
  synchronize-teams:
    runs-on: ubuntu-latest
    steps:
      - uses: rmacklin/team-sync@v0
        with:
          repo-token: "${{ secrets.BOT_PAT }}"
